"""
Phase 2 fine-tuning: continues training the DTLN model from the Phase 1
baseline checkpoint (models_phase1_baseline/phase1_baseline.weights.h5) on
the synthetic defence-noise set (data/processed/synthetic/{clean,noisy}),
using hyperparameters from configs/config.yaml's training.phase2_finetune
section. Goal: specialize the general-purpose Phase 1 model toward defence
noise types (bomb explosion, drone, gunshot, helicopter, siren, wind)
without discarding what Phase 1 learned, using a low learning rate.

COLAB SETUP NEEDED: same as train_baseline.py - Drive mounted, repo synced
to /content/drive/MyDrive/dtln-defence-speech-enhancement/, GPU runtime,
cd into the repo folder before running. Also needs
models_phase1_baseline/phase1_baseline.weights.h5 to already exist (synced
from Phase 1) - see FAILS LOUDLY note below.

TRAINING DATA MUST BE REGENERATED BEFORE EACH RUN THAT CHANGES THE NOISE
POOL: data/processed/synthetic/{clean,noisy} is built once by
data.prepare_dataset.build_synthetic_defence_set() and NOT regenerated by
this script. If the noise source pool changes (e.g. after fixing
train/test noise leakage by splitting into defence_noise_train and
defence_noise_test), that regeneration must happen and be synced to Drive
BEFORE running this script, or it will fine-tune on stale data.

MIRRORS train_baseline.py: does not call the vendored DTLN_model.py's own
compile_model()/train_model() (same outdated-API reasons as Phase 1) -
reuses build_DTLN_model(), lossWrapper()/snr_cost, and audio_generator
unchanged, reimplements compile/fit orchestration itself. Same
ReduceLROnPlateau / EarlyStopping / ModelCheckpoint / CSVLogger callback
setup as train_baseline.py, pointed at a separate phase2 save directory so
the phase1 checkpoint is never overwritten.

FAILS LOUDLY: if models_phase1_baseline/phase1_baseline.weights.h5 does not
exist, this script raises FileNotFoundError immediately instead of falling
back to a randomly initialized model. Fine-tuning from random weights would
silently defeat the entire point of Phase 2 (specializing an already-good
model), so this must never happen unnoticed.

BUGFIX NOTE: max_epochs was previously hardcoded to 60, silently ignoring
configs/config.yaml's training.phase2_finetune.epochs value (30). Now reads
epochs directly from that config key, so the config file is the actual
source of truth it claims to be. EarlyStopping (patience=15) may still
end a run before reaching whatever epoch count is configured either way.

TWO ASSUMPTIONS FLAGGED (not in configs/config.yaml, no locked decision on
these yet - confirm or correct):
1. chunk_length_seconds: training.phase2_finetune has no
   chunk_length_seconds field. This reuses the Phase 1 value (1.0s,
   hardcoded below as _CHUNK_LENGTH_SECONDS) since the same
   shortest-clip-length constraint applies (audio_generator silently
   produces 0 samples per file if this exceeds the shortest real clip).
   If your synthetic clips are a different typical length than
   VoiceBank-DEMAND's, this may need to change.
2. Train/val split: data/processed/synthetic/{clean,noisy} is flat (no
   train_val split from build_synthetic_defence_set()), so this script
   creates the split itself on first run into
   data/processed/synthetic/{clean_train,noisy_train,clean_val,noisy_val},
   using _VAL_FRACTION (0.1) of clean/noisy filename pairs, chosen with a
   fixed random seed (_SPLIT_SEED = 42) for reproducibility. If the split
   directories already exist with matching file counts, the split step is
   skipped (idempotent) rather than redone, so re-running this script does
   not reshuffle files that already have a fixed train/val assignment.
   IMPORTANT: if data/processed/synthetic/{clean,noisy} was regenerated
   (new noise pool), the OLD split directories from the previous noise
   pool will still be sitting on disk with a stale file count. The
   idempotent check compares train+val count against the CURRENT matched
   pairs count, so a mismatch triggers an automatic re-split - but delete
   the old split directories manually first if in doubt, rather than
   relying on the count-mismatch detection alone.

PREREQUISITE: run data.prepare_dataset.build_synthetic_defence_set() first
to produce data/processed/synthetic/{clean,noisy}.
"""

import os
import random
import shutil
import sys

import yaml
import tensorflow.keras as keras
from tensorflow.keras.callbacks import ReduceLROnPlateau, CSVLogger, \
    EarlyStopping, ModelCheckpoint

_EXTERNAL_DTLN_PATH = os.path.join(os.path.dirname(__file__), "../../external/DTLN")
sys.path.append(os.path.abspath(_EXTERNAL_DTLN_PATH))
from DTLN_model import DTLN_model, audio_generator

_CHUNK_LENGTH_SECONDS = 1.0
_VAL_FRACTION = 0.1
_SPLIT_SEED = 42

_PHASE1_CHECKPOINT = "./models_phase1_baseline/phase1_baseline.weights.h5"
_SYNTHETIC_DIR = "data/processed/synthetic"


def _load_config(config_path="configs/config.yaml"):
    with open(config_path, "r") as f:
        return yaml.safe_load(f)


def _split_synthetic_set(synthetic_dir=_SYNTHETIC_DIR, val_fraction=_VAL_FRACTION,
                          seed=_SPLIT_SEED):
    clean_dir = os.path.join(synthetic_dir, "clean")
    noisy_dir = os.path.join(synthetic_dir, "noisy")
    if not os.path.isdir(clean_dir) or not os.path.isdir(noisy_dir):
        raise FileNotFoundError(
            f"Expected {clean_dir} and {noisy_dir} to exist. Run "
            f"data.prepare_dataset.build_synthetic_defence_set() first."
        )

    out_dirs = {
        "clean_train": os.path.join(synthetic_dir, "clean_train"),
        "noisy_train": os.path.join(synthetic_dir, "noisy_train"),
        "clean_val": os.path.join(synthetic_dir, "clean_val"),
        "noisy_val": os.path.join(synthetic_dir, "noisy_val"),
    }

    clean_files = set(os.listdir(clean_dir))
    noisy_files = set(os.listdir(noisy_dir))
    matched = sorted(clean_files & noisy_files)
    if not matched:
        raise ValueError(
            f"No matching filenames between {clean_dir} and {noisy_dir}. "
            f"Cannot build a train/val split with zero matched pairs."
        )

    existing_train = os.path.isdir(out_dirs["clean_train"]) and \
        os.path.isdir(out_dirs["noisy_train"])
    existing_val = os.path.isdir(out_dirs["clean_val"]) and \
        os.path.isdir(out_dirs["noisy_val"])
    if existing_train and existing_val:
        train_count = len(os.listdir(out_dirs["clean_train"]))
        val_count = len(os.listdir(out_dirs["clean_val"]))
        if train_count + val_count == len(matched):
            print(
                f"Synthetic split already exists "
                f"({train_count} train, {val_count} val, "
                f"{len(matched)} total matched pairs) - skipping re-split."
            )
            return out_dirs
        print(
            f"WARNING: existing split file count ({train_count} train + "
            f"{val_count} val = {train_count + val_count}) does not match "
            f"current matched pairs ({len(matched)}). Re-splitting from "
            f"scratch."
        )
        for d in out_dirs.values():
            shutil.rmtree(d)

    rng = random.Random(seed)
    shuffled = list(matched)
    rng.shuffle(shuffled)
    val_count = max(1, int(len(shuffled) * val_fraction))
    val_files = set(shuffled[:val_count])
    train_files = [f for f in shuffled if f not in val_files]

    for d in out_dirs.values():
        os.makedirs(d, exist_ok=True)

    for fname in train_files:
        shutil.copy2(os.path.join(clean_dir, fname), os.path.join(out_dirs["clean_train"], fname))
        shutil.copy2(os.path.join(noisy_dir, fname), os.path.join(out_dirs["noisy_train"], fname))
    for fname in val_files:
        shutil.copy2(os.path.join(clean_dir, fname), os.path.join(out_dirs["clean_val"], fname))
        shutil.copy2(os.path.join(noisy_dir, fname), os.path.join(out_dirs["noisy_val"], fname))

    print(
        f"Split {len(matched)} matched pairs into {len(train_files)} train "
        f"and {len(val_files)} val (seed={seed}, val_fraction={val_fraction})."
    )
    return out_dirs


def finetune_defence(config_path="configs/config.yaml"):
    config = _load_config(config_path)
    audio_cfg = config["audio"]
    train_cfg = config["training"]["phase2_finetune"]

    if not os.path.isfile(_PHASE1_CHECKPOINT):
        raise FileNotFoundError(
            f"{_PHASE1_CHECKPOINT} not found. Phase 2 fine-tuning requires "
            f"a completed Phase 1 baseline checkpoint - run "
            f"src.training.train_baseline first, or sync the checkpoint "
            f"file from Drive if it was trained elsewhere. Refusing to "
            f"fall back to random-init weights."
        )

    split_dirs = _split_synthetic_set()

    dtln = DTLN_model()
    dtln.fs = audio_cfg["sample_rate"]
    dtln.blockLen = audio_cfg["frame_size_samples"]
    dtln.block_shift = audio_cfg["hop_size_samples"]
    dtln.batchsize = train_cfg["batch_size"]
    dtln.lr = train_cfg["learning_rate"]
    dtln.max_epochs = train_cfg["epochs"]
    dtln.len_samples = _CHUNK_LENGTH_SECONDS

    dtln.build_DTLN_model()
    dtln.model.load_weights(_PHASE1_CHECKPOINT)
    print(f"Loaded Phase 1 weights from {_PHASE1_CHECKPOINT}")
    print(f"Training for up to {dtln.max_epochs} epochs "
          f"(configs/config.yaml training.phase2_finetune.epochs)")

    optimizer = keras.optimizers.Adam(learning_rate=dtln.lr, clipnorm=3.0)
    dtln.model.compile(loss=dtln.lossWrapper(), optimizer=optimizer)

    save_path = "./models_phase2_finetune/"
    os.makedirs(save_path, exist_ok=True)
    checkpointer = ModelCheckpoint(
        os.path.join(save_path, "phase2_finetune.weights.h5"),
        monitor="val_loss", verbose=1, save_best_only=True,
        save_weights_only=True, mode="auto", save_freq="epoch",
    )
    reduce_lr = ReduceLROnPlateau(
        monitor="val_loss", factor=0.5, patience=3, min_lr=1e-10, cooldown=1
    )
    early_stopping = EarlyStopping(
        monitor="val_loss", min_delta=0, patience=15, verbose=0,
        mode="auto", baseline=None,
    )
    csv_logger = CSVLogger(os.path.join(save_path, "training.log"))

    len_in_samples = int((dtln.fs * dtln.len_samples // dtln.block_shift) * dtln.block_shift)

    train_gen = audio_generator(
        split_dirs["noisy_train"], split_dirs["clean_train"],
        len_in_samples, dtln.fs, train_flag=True,
    )
    train_dataset = train_gen.tf_data_set.batch(dtln.batchsize, drop_remainder=True).repeat()
    steps_train = train_gen.total_samples // dtln.batchsize

    val_gen = audio_generator(
        split_dirs["noisy_val"], split_dirs["clean_val"],
        len_in_samples, dtln.fs,
    )
    val_dataset = val_gen.tf_data_set.batch(dtln.batchsize, drop_remainder=True).repeat()
    steps_val = val_gen.total_samples // dtln.batchsize

    if steps_train == 0 or steps_val == 0:
        raise ValueError(
            f"Not enough audio to form a full batch (steps_train={steps_train}, "
            f"steps_val={steps_val}). Reduce batch_size in configs/config.yaml "
            f"or add more synthetic data."
        )

    history = dtln.model.fit(
        x=train_dataset,
        steps_per_epoch=steps_train,
        epochs=dtln.max_epochs,
        verbose=1,
        validation_data=val_dataset,
        validation_steps=steps_val,
        callbacks=[checkpointer, reduce_lr, csv_logger, early_stopping],
    )

    return history


if __name__ == "__main__":
    finetune_defence()